---

language: python
python: 2.7
sudo: required

services:
  - docker

# Install requirements
install:
  - pip install tox-travis

# Test all the scenarios against the Ansible versions defined in the tox.ini file
script:
  - tox
