version: '3.1'

services:
  app:
    image: fminzoni/ecs-example
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        deployer.port: 80
        deployer.domain: example.entercloudsuite.com
